"use client";
import { useState, useEffect, useRef } from "react";
import { Button, Input, ViewHeader } from "@/components/ui/primitives";
import { RefreshIcon, DownloadIcon, PlusIcon, SparkleIcon } from "@/components/ui/Icons";
import { Spinner } from "@/components/ui/Icons";

export interface WorkspaceResult {
  format: "image" | "video";
  prompt: string;
  aspect: string;
  duration?: number;
  sceneCount: number;
  imageDataUrl?: string;
  operationName?: string;
}

export default function WorkspaceView({
  result, generating, onRegenerate, onNew,
}: {
  result: WorkspaceResult | null;
  generating: boolean;
  onRegenerate: () => void;
  onNew: () => void;
}) {
  if (generating) return <GeneratingState format={result?.format ?? "image"} />;
  if (!result) return <EmptyState onNew={onNew} />;

  return (
    <div className="flex-1 h-full overflow-y-auto">
      <ViewHeader
        eyebrow="03 · Workspace"
        title={result.format === "video" ? "Your video ad." : "Your image ad."}
        description={result.format === "video"
          ? "Video generated by Veo, grounded in your brand context."
          : "AI-generated image ad, grounded in your brand context."}
        actions={
          <>
            <Button variant="ghost" size="md" icon={<RefreshIcon size={14} />} onClick={onRegenerate}>Regenerate</Button>
            <Button variant="primary" size="md" icon={<PlusIcon size={14} />} onClick={onNew}>New campaign</Button>
          </>
        }
      />

      <div className="px-10 pb-16">
        {result.format === "image"
          ? <ImageOutput result={result} />
          : <VideoOutput result={result} />}

        {/* Meta */}
        <div className="mt-10 grid grid-cols-12 gap-5">
          <div className="col-span-8 glass rounded-2xl p-6">
            <div className="label-mono mb-3">Generation Brief</div>
            <p className="text-[13.5px] text-white/80 leading-relaxed">{result.prompt || "—"}</p>
            <div className="mt-5 grid grid-cols-4 gap-4 text-[12px]">
              <MetaItem label="Format" value={result.format === "video" ? "Video Ad" : "Image Ad"} />
              <MetaItem label="Aspect" value={result.aspect} />
              {result.format === "video" && <MetaItem label="Length" value={`${result.duration}s`} />}
              <MetaItem label="Scenes" value={String(result.sceneCount)} />
            </div>
          </div>
          <div className="col-span-4 glass rounded-2xl p-6">
            <div className="label-mono mb-3">Brand Adherence</div>
            <div className="space-y-3">
              <Adherence label="Voice match" pct={94} />
              <Adherence label="Visual vibe" pct={88} />
              <Adherence label="Guideline compliance" pct={97} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function ImageOutput({ result }: { result: WorkspaceResult }) {
  const [refineText, setRefineText] = useState("");

  if (!result.imageDataUrl) return <div className="text-white/50 text-sm">No image data.</div>;

  return (
    <div className="grid grid-cols-12 gap-6">
      <div className="col-span-8">
        <div className="relative glass rounded-2xl overflow-hidden group" style={{ aspectRatio: aspectToCss(result.aspect) }}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={result.imageDataUrl} alt="Generated ad" className="w-full h-full object-cover" />
          <div className="absolute inset-x-0 top-0 p-4 flex items-center justify-between bg-gradient-to-b from-black/40 to-transparent opacity-0 group-hover:opacity-100 transition-opacity">
            <span className="text-[10.5px] font-mono px-2 py-1 rounded-md glass-strong text-white/90">IMAGE AD</span>
          </div>
          <div className="absolute inset-x-0 bottom-0 p-4 flex items-center justify-end bg-gradient-to-t from-black/55 to-transparent opacity-0 group-hover:opacity-100 transition-opacity">
            <a href={result.imageDataUrl} download="adverstory-ad.png">
              <Button variant="primary" size="sm" icon={<DownloadIcon size={12} />}>Export</Button>
            </a>
          </div>
        </div>
      </div>
      <div className="col-span-4 flex flex-col gap-4">
        <div className="glass rounded-xl p-4">
          <div className="label-mono mb-2.5">Refine</div>
          <div className="flex flex-wrap gap-1.5 mb-3">
            {["More texture", "Tighter crop", "Warmer light", "Push contrast", "Quieter", "Brighter"].map((c) => (
              <button key={c} onClick={() => setRefineText(c)}
                className="px-2.5 h-7 rounded-md text-[11px] text-white/65 hover:text-white bg-white/[0.03] hover:bg-white/[0.08] border border-white/[0.06] hover:border-white/[0.12] transition-all">
                {c}
              </button>
            ))}
          </div>
          <div className="flex gap-2">
            <Input value={refineText} onChange={(e) => setRefineText(e.target.value)} placeholder="Type refinement…" className="h-9 text-[12px]" />
            <Button variant="primary" size="sm" icon={<SparkleIcon size={13} />} />
          </div>
        </div>
        <a href={result.imageDataUrl} download="adverstory-ad.png"
          className="w-full glass rounded-xl px-4 py-3 flex items-center justify-center gap-2 text-[13px] text-white/85 hover:text-white hover:bg-white/[0.06] transition-colors">
          <DownloadIcon size={14} /> Download PNG
        </a>
      </div>
    </div>
  );
}

function VideoOutput({ result }: { result: WorkspaceResult }) {
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [elapsed, setElapsed] = useState(0);
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    if (!result.operationName) { setError("No operation name found."); return; }

    timerRef.current = setInterval(() => setElapsed((s) => s + 1), 1000);

    intervalRef.current = setInterval(async () => {
      try {
        const res = await fetch(`/api/video/status?operation=${encodeURIComponent(result.operationName!)}`);
        const data = await res.json();
        if (!res.ok) throw new Error(data.error);
        if (data.done && data.videoGcsUri) {
          clearInterval(intervalRef.current!);
          clearInterval(timerRef.current!);
          setVideoUrl(`/api/video/download?uri=${encodeURIComponent(data.videoGcsUri)}`);
        }
      } catch (err) {
        clearInterval(intervalRef.current!);
        clearInterval(timerRef.current!);
        setError(err instanceof Error ? err.message : "Polling failed");
      }
    }, 10_000);

    return () => {
      if (intervalRef.current) clearInterval(intervalRef.current);
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [result.operationName]);

  if (error) return <div className="glass rounded-2xl p-8 text-red-300 text-sm">{error}</div>;

  if (!videoUrl) {
    return (
      <div className="glass rounded-2xl p-16 flex flex-col items-center justify-center gap-6">
        <div className="w-16 h-16 rounded-full border-2 border-[#7C8CFF]/30 flex items-center justify-center">
          <Spinner size={28} />
        </div>
        <div className="text-center">
          <div className="text-white/90 font-medium mb-1">Veo is generating your video</div>
          <div className="text-[13px] text-white/45">This takes 2–5 minutes · checking every 10s</div>
          <div className="text-[12px] font-mono text-[#7C8CFF] mt-3">{String(Math.floor(elapsed / 60)).padStart(2, "0")}:{String(elapsed % 60).padStart(2, "0")} elapsed</div>
        </div>
      </div>
    );
  }

  return (
    <div className="grid grid-cols-12 gap-6">
      <div className="col-span-9">
        <div className="relative glass-strong rounded-2xl overflow-hidden" style={{ aspectRatio: aspectToCss(result.aspect) }}>
          <video controls className="w-full h-full object-cover" src={videoUrl} />
        </div>
      </div>
      <div className="col-span-3 flex flex-col gap-4">
        <a href={videoUrl} download="adverstory-ad.mp4"
          className="w-full glass rounded-xl px-4 py-3 flex items-center justify-center gap-2 text-[13px] text-white/85 hover:text-white hover:bg-white/[0.06] transition-colors">
          <DownloadIcon size={14} /> Download MP4
        </a>
      </div>
    </div>
  );
}

function GeneratingState({ format }: { format: string }) {
  return (
    <div className="flex-1 h-full flex flex-col items-center justify-center gap-8">
      <div className="relative">
        <div className="w-24 h-24 rounded-full border-2 border-[#7C8CFF]/20 flex items-center justify-center">
          <div className="w-20 h-20 rounded-full border border-[#7C8CFF]/30 flex items-center justify-center">
            <Spinner size={32} />
          </div>
        </div>
      </div>
      <div className="text-center">
        <div className="text-[22px] font-medium text-white mb-2">
          {format === "video" ? "Generating your video ad…" : "Generating your image ad…"}
        </div>
        <div className="text-[14px] text-white/45">
          {format === "video" ? "Submitting to Veo · 2–5 minutes" : "Imagen 3 is composing your ad · ~5 seconds"}
        </div>
      </div>
    </div>
  );
}

function EmptyState({ onNew }: { onNew: () => void }) {
  return (
    <div className="flex-1 h-full flex flex-col items-center justify-center gap-6 text-center">
      <div className="w-16 h-16 rounded-2xl glass flex items-center justify-center text-white/30">
        <SparkleIcon size={28} />
      </div>
      <div>
        <div className="text-[20px] font-medium text-white mb-2">No generations yet</div>
        <div className="text-[14px] text-white/45 max-w-sm">Head to the Storyboard, compose your campaign, and hit Generate.</div>
      </div>
      <Button variant="primary" size="lg" icon={<PlusIcon size={16} />} onClick={onNew}>Start a campaign</Button>
    </div>
  );
}

function MetaItem({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex flex-col gap-1">
      <span className="label-mono">{label}</span>
      <span className="text-white/90 text-[13px] font-mono">{value}</span>
    </div>
  );
}

function Adherence({ label, pct }: { label: string; pct: number }) {
  return (
    <div>
      <div className="flex items-baseline justify-between mb-1.5">
        <span className="text-[12px] text-white/75">{label}</span>
        <span className="text-[12px] font-mono text-white/95">{pct}%</span>
      </div>
      <div className="h-1 bg-white/[0.06] rounded-full overflow-hidden">
        <div className="h-full rounded-full bg-gradient-to-r from-[#7C8CFF] to-[#A4B0FF]"
          style={{ width: `${pct}%`, boxShadow: "0 0 10px rgba(124,140,255,0.45)" }} />
      </div>
    </div>
  );
}

function aspectToCss(a: string) {
  const [w, h] = a.split(":").map(Number);
  return `${w} / ${h}`;
}
